default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railsloja_dev

test:
  <<: *default
  database: railsloja_test

production:
  <<: *default
  database: railsloja_prod